In [2]:
import numpy as np

In [1]:
arr = np.array([28,30,29,31,32,30,29])
print(arr.mean())
print(arr.max())
print(arr.min())
print(len(arr[arr > 30]))
print(np.where(arr > 30, arr, 0))
print(np.count_nonzero(np.where(arr > 30, arr, 0)))

NameError: name 'np' is not defined

In [11]:
marks = np.array([85,90,78,92,88])
print(np.mean(marks))
print(np.sort(marks))
print(np.median(marks))
print(np.std(marks))
print(marks/10)

86.6
[78 85 88 90 92]
88.0
4.882622246293481
[8.5 9.  7.8 9.2 8.8]


In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A+B)
print(A * B)
print(A @ B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [27]:
arr2 = np.random.randint(0,10,(3,4))
print(arr2)
print(np.max(arr2,axis = 0))
print(np.min(arr2,axis = 1))
print(np.where(arr2 % 2 == 0, arr2, -1))
arr2[arr2 % 2 == 1] = -1
print(arr2)

[[2 2 8 0]
 [8 6 1 6]
 [7 0 9 5]]
[8 6 9 6]
[0 1 0]
[[ 2  2  8  0]
 [ 8  6 -1  6]
 [-1  0 -1 -1]]
[[ 2  2  8  0]
 [ 8  6 -1  6]
 [-1  0 -1 -1]]


In [33]:
arr3 = np.arange(1,13)
print(arr3)
print(np.reshape(arr3,(3,4)))
arr3 = np.reshape(arr3,(3,4))
print(np.sum(arr3,axis=1))
print(np.mean(arr3,axis=0))
print(np.reshape(arr3,(12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
arr4 = np.random.randint(0,20,(5,5))
print(arr4)
print(arr4[arr4 > 10])
print(np.where(arr4 > 10, 0, arr4))

[[ 0  2 16  4  1]
 [ 1  1  3 11 10]
 [ 2 10  5 18 13]
 [ 0  9 13  1 14]
 [ 9 13 18 17 19]]
[16 11 18 13 13 14 13 18 17 19]
[[ 0  2  0  4  1]
 [ 1  1  3  0 10]
 [ 2 10  5  0  0]
 [ 0  9  0  1  0]
 [ 9  0  0  0  0]]


In [ ]:
arrA = np.array([1,2,3])
arrB = np.array([4,5,6])
print(np.concatenate((arrA, arrB)))

In [40]:
arr5 = np.array([2,1,2,3,1,4,3])
unique_var,counts = np.unique(arr5,return_counts=True)
print(unique_var)
print(counts)
for val in unique_var:
    print(len(arr5[arr5 == val]))

[1 2 3 4]
[2 2 2 1]
2
2
2
1
