In [3]:
print([
    "Hello, World!",
    "This is my first note in a Jupyter Notebook.",
    "I'm excited to learn more about data science and programming!"])

['Hello, World!', 'This is my first note in a Jupyter Notebook.', "I'm excited to learn more about data science and programming!"]


In [5]:
print('a')

a


In [6]:
import numpy as np

In [7]:
print(np.array(1))

1


In [8]:
print(np.array([1,2,3]))

[1 2 3]


In [9]:
print(np.array([1,2,3]).ndim)
print(np.array([1,2,3]).shape)

1
(3,)


In [12]:
arr1 = np.zeros((2,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
arr2 = np.ones((2,3),dtype=int)
print(arr2)

[[1 1 1]
 [1 1 1]]


In [29]:
arr3 = np.empty((4,3),dtype=int)
print(arr3)

[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]


In [31]:
arr4 = np.full((2,3),45)
print(arr4)

[[45 45 45]
 [45 45 45]]


In [33]:
lists = [[1,2,3],[4,5,6]]
arr5 = np.array(lists)
print(arr5)

[[1 2 3]
 [4 5 6]]


In [35]:
arr6 = np.full_like(arr5, 7)
print(arr6)

[[7 7 7]
 [7 7 7]]


In [38]:
arr7= np.arange(2,10,2)
print(arr7)

[2 4 6 8]


In [41]:
arr8 = np.linspace(1,10,4,dtype=float)
print(arr8)

[ 1.  4.  7. 10.]


In [45]:
arr9 = np.logspace((1,4),2,2,dtype=int)
print(arr9)

[[   10 10000]
 [  100   100]]


In [48]:
arr10 = np.eye(3,3)
print(arr10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
arr11 = np.diag([1,2,3])
print(arr11)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [56]:
np.random.seed(40)
arr12 = np.random.rand(2,3)
print(arr12)
arr13 = np.random.randn(3,4)
print(arr13)
arr14 = np.random.uniform(2,3, (2,3))
print(arr14)

[[0.40768703 0.05536604 0.78853488]
 [0.28730518 0.45035059 0.30391231]]
[[ 2.29249034  0.48881005  0.71026699  1.05553444]
 [ 0.0540731   0.25795342  0.58828165  0.88524424]
 [-1.01700702 -0.13369303 -0.4381855   0.49344349]]
[[2.17420267 2.44914708 2.66979478]
 [2.95739911 2.83333325 2.50830996]]
